server:
  port: 8080

spring:
  application:
    name: vibeMusic-backend

  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/vibemusic?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Redis 配置
  data:
    redis:
      host: localhost
      port: 6379
      # password:               # 没有密码，留空
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml   # XML 映射文件路径
  configuration:
    map-underscore-to-camel-case: true    # 下划线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台打印 SQL
  global-config:
    db-config:
      id-type: auto                       # 主键自增
      logic-delete-field: deleted         # 逻辑删除字段（暂未使用）
      logic-delete-value: 1
      logic-not-delete-value: 0

# JWT 配置
jwt:
  secret: SyQ8bG9uZ1NlY3JldEtleUZvclZpYmVNdXNpY1Byb2plY3QyMDI2          # 生产环境务必修改为复杂密钥
  expiration: 86400000            # Token 有效期（毫秒）默认 24 小时

# 网易云 API 配置
netease:
  api:
    base-url: http://localhost:3000
    timeout: 10000
    cookie: "MUSIC_U=00F50692DDA9F401BE9A5A1F69D4CC0FDD02CD4FDDBC58AB16F4DC891EE714A96E1CDE27FDC006F7F1718920B010B5ACEFB42085392662AF45D0A5462C3FA56462714D5CA8981D25C54FF963DA4429C8492F450F4D1A6E18D1E4964152C9B570AD590BFD502041CE5452A12C4498B0DAF52A33AEFE4F7F67ECFE02C414320C8BDDE52CC1ED8EAC6DF60AAFF0648EF999C0F451E2AA665FAC1549F23618B2BAE77AF45656ECD9755430D0D939A34B146F359F8A6BD821C0809A3792DD6C5A8407C242C1ED9FD400BE84B01BDEC11CD0081BFE49B7870478C13BDD572A98DE560ACD9FBC065F2360E78323AD62804C3CAB3FD5BB6E6DD7E525945D38AE4772B2022DF8A66DFB9099C647102943406DF3B62DEDA0D646EC0499B02732E53176A1E8167D8042480AC2CC486DE2171E2037B354C3CA6CAA2086DB6770481950F756C6747F631A19BD065735EC4FD68DFC5E51DE8516B6039A4C52676C85A9C30A0E6EE0C145B4BC36F6D3967627ADF7F9BB9B1BD1A21BD7AD863002AD0292617EC987BB833771BB4E2BF092DB32D769D8A1061617A6EDEFC9301B5F5CBBBB25CE2E16CD; __csrf=8bf9acb3aeadbb8cad9650355bdbe0a4; _iuqxldmzr_=32; _ntes_nuid=36e330fdee9ad9b35f2eaa6aab5a9dac; _ntes_nnid=36e330fdee9ad9b35f2eaa6aab5a9dac,1765033101857"

# RustFS 对象存储配置
storage:
  rustfs:
    endpoint: http://127.0.0.1:9000
    access-key: rustfsadmin
    secret-key: rustfsadmin
    bucket-name: vibemusic
    data-path: D:\Rustfsdata

# Knife4j API 文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.vibemusic

knife4j:
  enable: true
  setting:
    language: zh_cn

# 日志级别
logging:
  level:
    com.vibemusic: debug
    org.springframework.security: debug
